
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The target system is: Windows - 10.0 - AMD64
      The host system is: Linux - 6.6.14-200.fc39.x86_64 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/clang-cl 
      Build flags: -Xclang;-fpass-plugin=/opt/winsdk/llvm-passes/libBogusControlFlow.so
      Id flags:  
      
      The output was:
      1
      clang-cl: warning: unable to find a Visual Studio installation; try running Clang from a developer command prompt [-Wmsvc-not-found]
      Start BogusControlFlow Pass.
      FunctionName: main
      Finished BogusControlFlow Pass.
      clang-cl: error: unable to execute command: Executable "link.exe" doesn't exist!
      clang-cl: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/clang-cl 
      Build flags: -Xclang;-fpass-plugin=/opt/winsdk/llvm-passes/libBogusControlFlow.so
      Id flags: -c 
      
      The output was:
      0
      Start BogusControlFlow Pass.
      FunctionName: main
      Finished BogusControlFlow Pass.
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.obj"
      
      The C compiler identification is Clang, found in:
        /opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/3.27.7/CompilerIdC/CMakeCCompilerId.obj
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:1155 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        Note: including file: ./foo.h
        Start BogusControlFlow Pass.
        FunctionName: main
        Finished BogusControlFlow Pass.
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe"
      binary: "/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe"
    cmakeVariables:
      CMAKE_C_FLAGS: "-Xclang -fpass-plugin=/opt/winsdk/llvm-passes/libBogusControlFlow.so /winsdkdir /opt/winsdk/sdk  /vctoolsdir /opt/winsdk/crt /DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/winsdkdir:/opt/winsdk/sdk  /vctoolsdir:/opt/winsdk/crt /MANIFEST:NO /machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_eb871/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_eb871.dir/build.make CMakeFiles/cmTC_eb871.dir/build
        gmake[1]: Entering directory '/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe'
        Building C object CMakeFiles/cmTC_eb871.dir/CMakeCCompilerABI.c.obj
        /usr/bin/clang-cl  /nologo  -imsvc/opt/winsdk/crt/include/CodeAnalysis/ConcurrencyCheck -imsvc/opt/winsdk/crt/include/CodeAnalysis/CppCoreCheck -imsvc/opt/winsdk/crt/include/CodeAnalysis/EnumIndex -imsvc/opt/winsdk/crt/include/CodeAnalysis/HResultCheck -imsvc/opt/winsdk/crt/include/CodeAnalysis/VariantClear -imsvc/opt/winsdk/crt/include/CodeAnalysis -imsvc/opt/winsdk/crt/include -imsvc/opt/winsdk/crt/include/msclr -imsvc/opt/winsdk/crt/include/msclr/com -imsvc/opt/winsdk/sdk/include/cppwinrt/winrt -imsvc/opt/winsdk/sdk/include/cppwinrt/winrt/impl -imsvc/opt/winsdk/sdk/include/shared -imsvc/opt/winsdk/sdk/include/shared/ndis -imsvc/opt/winsdk/sdk/include/shared/netcx/shared/net -imsvc/opt/winsdk/sdk/include/shared/netcx/shared/net/wifi -imsvc/opt/winsdk/sdk/include/ucrt -imsvc/opt/winsdk/sdk/include/ucrt/sys -imsvc/opt/winsdk/sdk/include/um -imsvc/opt/winsdk/sdk/include/um/alljoyn_c -imsvc/opt/winsdk/sdk/include/um/gl -imsvc/opt/winsdk/sdk/include/um/qcc -imsvc/opt/winsdk/sdk/include/um/qcc/windows -imsvc/opt/winsdk/sdk/include/um/winsqlite -imsvc/opt/winsdk/sdk/include/winrt -imsvc/opt/winsdk/sdk/include/winrt/wrl -imsvc/opt/winsdk/sdk/include/winrt/wrl/wrappers -Xclang -fpass-plugin=/opt/winsdk/llvm-passes/libBogusControlFlow.so /winsdkdir /opt/winsdk/sdk  /vctoolsdir /opt/winsdk/crt /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /FoCMakeFiles/cmTC_eb871.dir/CMakeCCompilerABI.c.obj /FdCMakeFiles/cmTC_eb871.dir/ -c -- /usr/share/cmake/Modules/CMakeCCompilerABI.c
        Start BogusControlFlow Pass.
        FunctionName: main
        Finished BogusControlFlow Pass.
        Linking C executable cmTC_eb871.exe
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_eb871.dir/link.txt --verbose=1
        /usr/bin/cmake -E vs_link_exe --intdir=CMakeFiles/cmTC_eb871.dir --rc=/usr/bin/llvm-rc --mt=/usr/bin/llvm-mt --manifests -- /usr/bin/lld-link /nologo @CMakeFiles/cmTC_eb871.dir/objects1.rsp  /out:cmTC_eb871.exe /implib:cmTC_eb871.lib /pdb:/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe/cmTC_eb871.pdb /version:0.0 /winsdkdir:/opt/winsdk/sdk  /vctoolsdir:/opt/winsdk/crt /MANIFEST:NO /machine:x64  /debug /INCREMENTAL /subsystem:console 
        Visual Studio Incremental Link without manifests
        LINK:
        /usr/bin/lld-link /nologo @CMakeFiles/cmTC_eb871.dir/objects1.rsp /out:cmTC_eb871.exe /implib:cmTC_eb871.lib /pdb:/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe/cmTC_eb871.pdb /version:0.0 /winsdkdir:/opt/winsdk/sdk /vctoolsdir:/opt/winsdk/crt /MANIFEST:NO /machine:x64 /debug /INCREMENTAL /subsystem:console
        gmake[1]: Leaving directory '/opt/winsdk/LLVM-Obfuscation-Experiments/malware/mimikatz/mimikatz/buildbogus/CMakeFiles/CMakeScratch/TryCompile-9OCtVe'
        
      exitCode: 0
...
